import { Team } from '../../types';

export const aacTeams: Team[] = [
  {
    teamId: 1,
    schoolName: 'Army',
    city: 'West Point',
    state: 'New York',
    latitude: 41.3834,
    longitude: -73.9558,
    nickname: 'Black Knights',
    logo: '',
    conference: 'AAC',
    elo: 801,
  },
  {
    teamId: 2,
    schoolName: 'Charlotte',
    city: 'Charlotte',
    state: 'North Carolina',
    latitude: 35.3076,
    longitude: -80.7350,
    nickname: '49ers',
    logo: '',
    conference: 'AAC',
    elo: 9629,
  },
  {
    teamId: 3,
    schoolName: 'East Carolina',
    city: 'Greenville',
    state: 'North Carolina',
    latitude: 35.6057,
    longitude: -77.3645,
    nickname: 'Pirates',
    logo: '',
    conference: 'AAC',
    elo: 3343,
  },
  {
    teamId: 4,
    schoolName: 'Florida Atlantic',
    city: 'Boca Raton',
    state: 'Florida',
    latitude: 26.3730,
    longitude: -80.1011,
    nickname: 'Owls',
    logo: '',
    conference: 'AAC',
    elo: 828,
  },
  {
    teamId: 5,
    schoolName: 'Memphis',
    city: 'Memphis',
    state: 'Tennessee',
    latitude: 35.1187,
    longitude: -89.9373,
    nickname: 'Tigers',
    logo: '',
    conference: 'AAC',
    elo: 2714,
  },
  {
    teamId: 6,
    schoolName: 'Navy',
    city: 'Annapolis',
    state: 'Maryland',
    latitude: 38.9859,
    longitude: -76.4838,
    nickname: 'Midshipmen',
    logo: '',
    conference: 'AAC',
    elo: 1601,
  },
  {
    teamId: 7,
    schoolName: 'North Texas',
    city: 'Denton',
    state: 'Texas',
    latitude: 33.2076,
    longitude: -97.1527,
    nickname: 'Mean Green',
    logo: '',
    conference: 'AAC',
    elo: 2939,
  },
  {
    teamId: 8,
    schoolName: 'Rice',
    city: 'Houston',
    state: 'Texas',
    latitude: 29.7174,
    longitude: -95.4018,
    nickname: 'Owls',
    logo: '',
    conference: 'AAC',
    elo: 5661,
  },
  {
    teamId: 9,
    schoolName: 'South Florida',
    city: 'Tampa',
    state: 'Florida',
    latitude: 28.0587,
    longitude: -82.4139,
    nickname: 'Bulls',
    logo: '',
    conference: 'AAC',
    elo: 6984,
  },
  {
    teamId: 10,
    schoolName: 'Temple',
    city: 'Philadelphia',
    state: 'Pennsylvania',
    latitude: 39.9812,
    longitude: -75.1550,
    nickname: 'Owls',
    logo: '',
    conference: 'AAC',
    elo: 6931,
  },
  {
    teamId: 11,
    schoolName: 'Tulane',
    city: 'New Orleans',
    state: 'Louisiana',
    latitude: 29.9409,
    longitude: -90.1203,
    nickname: 'Green Wave',
    logo: '',
    conference: 'AAC',
    elo: 3760,
  },
  {
    teamId: 12,
    schoolName: 'Tulsa',
    city: 'Tulsa',
    state: 'Oklahoma',
    latitude: 36.1532,
    longitude: -95.9457,
    nickname: 'Golden Hurricane',
    logo: '',
    conference: 'AAC',
    elo: 622,
  },
  {
    teamId: 13,
    schoolName: 'UAB',
    city: 'Birmingham',
    state: 'Alabama',
    latitude: 33.5020,
    longitude: -86.8063,
    nickname: 'Blazers',
    logo: '',
    conference: 'AAC',
    elo: 2737,
  },
  {
    teamId: 14,
    schoolName: 'UTSA',
    city: 'San Antonio',
    state: 'Texas',
    latitude: 29.5820,
    longitude: -98.6209,
    nickname: 'Roadrunners',
    logo: '',
    conference: 'AAC',
    elo: 6450,
  },
];

