import { Team } from '../../types';

export const accTeams: Team[] = [
  {
    teamId: 15,
    schoolName: 'Boston College',
    city: 'Chestnut Hill',
    state: 'Massachusetts',
    latitude: 42.3355,
    longitude: -71.1685,
    nickname: 'Eagles',
    logo: '',
    conference: 'ACC',
    elo: 7853,
  },
  {
    teamId: 16,
    schoolName: 'Clemson',
    city: 'Clemson',
    state: 'South Carolina',
    latitude: 34.6834,
    longitude: -82.8374,
    nickname: 'Tigers',
    logo: '',
    conference: 'ACC',
    elo: 2129,
  },
  {
    teamId: 17,
    schoolName: 'Duke',
    city: 'Durham',
    state: 'North Carolina',
    latitude: 36.0014,
    longitude: -78.9382,
    nickname: 'Blue Devils',
    logo: '',
    conference: 'ACC',
    elo: 6751,
  },
  {
    teamId: 18,
    schoolName: 'Florida State',
    city: 'Tallahassee',
    state: 'Florida',
    latitude: 30.4419,
    longitude: -84.2985,
    nickname: 'Seminoles',
    logo: '',
    conference: 'ACC',
    elo: 8965,
  },
  {
    teamId: 19,
    schoolName: 'Georgia Tech',
    city: 'Atlanta',
    state: 'Georgia',
    latitude: 33.7756,
    longitude: -84.3963,
    nickname: 'Yellow Jackets',
    logo: '',
    conference: 'ACC',
    elo: 1068,
  },
  {
    teamId: 20,
    schoolName: 'Louisville',
    city: 'Louisville',
    state: 'Kentucky',
    latitude: 38.2151,
    longitude: -85.7585,
    nickname: 'Cardinals',
    logo: '',
    conference: 'ACC',
    elo: 1303,
  },
  {
    teamId: 21,
    schoolName: 'Miami',
    city: 'Coral Gables',
    state: 'Florida',
    latitude: 25.7173,
    longitude: -80.277,
    nickname: 'Hurricanes',
    logo: '',
    conference: 'ACC',
    elo: 1427,
  },
  {
    teamId: 22,
    schoolName: 'North Carolina State',
    city: 'Raleigh',
    state: 'North Carolina',
    latitude: 35.7847,
    longitude: -78.6821,
    nickname: 'Wolfpack',
    logo: '',
    conference: 'ACC',
    elo: 4380,
  },
  {
    teamId: 23,
    schoolName: 'North Carolina',
    city: 'Chapel Hill',
    state: 'North Carolina',
    latitude: 35.9049,
    longitude: -79.0469,
    nickname: 'Tar Heels',
    logo: '',
    conference: 'ACC',
    elo: 4039,
  },
  {
    teamId: 24,
    schoolName: 'Pitt',
    city: 'Pittsburgh',
    state: 'Pennsylvania',
    latitude: 40.4443,
    longitude: -79.9608,
    nickname: 'Panthers',
    logo: '',
    conference: 'ACC',
    elo: 9546,
  },
  {
    teamId: 25,
    schoolName: 'Syracuse',
    city: 'Syracuse',
    state: 'New York',
    latitude: 43.0392,
    longitude: -76.1351,
    nickname: 'Orange',
    logo: '',
    conference: 'ACC',
    elo: 1094,
  },
  {
    teamId: 26,
    schoolName: 'Virginia',
    city: 'Charlottesville',
    state: 'Virginia',
    latitude: 38.0336,
    longitude: -78.508,
    nickname: 'Cavaliers',
    logo: '',
    conference: 'ACC',
    elo: 8679,
  },
  {
    teamId: 27,
    schoolName: 'Virginia Tech',
    city: 'Blacksburg',
    state: 'Virginia',
    latitude: 37.2307,
    longitude: -80.4215,
    nickname: 'Hokies',
    logo: '',
    conference: 'ACC',
    elo: 5198,
  },
  {
    teamId: 28,
    schoolName: 'Wake Forest',
    city: 'Winston-Salem',
    state: 'North Carolina',
    latitude: 36.1351,
    longitude: -80.2796,
    nickname: 'Demon Deacons',
    logo: '',
    conference: 'ACC',
    elo: 1802,
  },
  {
    teamId: 29,
    schoolName: 'Southern Methodist',
    city: 'Dallas',
    state: 'Texas',
    latitude: 32.8418,
    longitude: -96.7846,
    nickname: 'Mustangs',
    logo: '',
    conference: 'ACC',
    elo: 5100,
  },
  {
    teamId: 30,
    schoolName: 'Stanford',
    city: 'Stanford',
    state: 'California',
    latitude: 37.4275,
    longitude: -122.1697,
    nickname: 'Cardinal',
    logo: '',
    conference: 'ACC',
    elo: 9167,
  },
  {
    teamId: 31,
    schoolName: 'California',
    city: 'Berkeley',
    state: 'California',
    latitude: 37.8719,
    longitude: -122.2585,
    nickname: 'Golden Bears',
    logo: '',
    conference: 'ACC',
    elo: 6755,
  },
];
