import { Team } from '../../types';

export const big10Teams: Team[] = [
  {
    teamId: 32,
    schoolName: 'Illinois',
    city: 'Champaign',
    state: 'Illinois',
    latitude: 40.1106,
    longitude: -88.2073,
    nickname: 'Fighting Illini',
    logo: '',
    conference: 'Big 10',
    elo: 5000,
  },
  {
    teamId: 33,
    schoolName: 'Indiana',
    city: 'Bloomington',
    state: 'Indiana',
    latitude: 39.1653,
    longitude: -86.5264,
    nickname: 'Hoosiers',
    logo: '',
    conference: 'Big 10',
    elo: 5000,
  },
  {
    teamId: 34,
    schoolName: 'Iowa',
    city: 'Iowa City',
    state: 'Iowa',
    latitude: 41.6611,
    longitude: -91.5302,
    nickname: 'Hawkeyes',
    logo: '',
    conference: 'Big 10',
    elo: 5000,
  },
  {
    teamId: 35,
    schoolName: 'Maryland',
    city: 'College Park',
    state: 'Maryland',
    latitude: 38.9862,
    longitude: -76.9426,
    nickname: 'Terrapins',
    logo: '',
    conference: 'Big 10',
    elo: 5000,
  },
  {
    teamId: 36,
    schoolName: 'Michigan',
    city: 'Ann Arbor',
    state: 'Michigan',
    latitude: 42.2780,
    longitude: -83.7382,
    nickname: 'Wolverines',
    logo: '',
    conference: 'Big 10',
    elo: 5000,
  },
  {
    teamId: 37,
    schoolName: 'Michigan State',
    city: 'East Lansing',
    state: 'Michigan',
    latitude: 42.7325,
    longitude: -84.4822,
    nickname: 'Spartans',
    logo: '',
    conference: 'Big 10',
    elo: 5000,
  },
  {
    teamId: 38,
    schoolName: 'Minnesota',
    city: 'Minneapolis',
    state: 'Minnesota',
    latitude: 44.9763,
    longitude: -93.2336,
    nickname: 'Golden Gophers',
    logo: '',
    conference: 'Big 10',
    elo: 5000,
  },
  {
    teamId: 39,
    schoolName: 'Nebraska',
    city: 'Lincoln',
    state: 'Nebraska',
    latitude: 40.8136,
    longitude: -96.7026,
    nickname: 'Cornhuskers',
    logo: '',
    conference: 'Big 10',
    elo: 5000,
  },
  {
    teamId: 40,
    schoolName: 'Northwestern',
    city: 'Evanston',
    state: 'Illinois',
    latitude: 42.0623,
    longitude: -87.6756,
    nickname: 'Wildcats',
    logo: '',
    conference: 'Big 10',
    elo: 5000,
  },
  {
    teamId: 41,
    schoolName: 'Ohio State',
    city: 'Columbus',
    state: 'Ohio',
    latitude: 40.0028,
    longitude: -83.0194,
    nickname: 'Buckeyes',
    logo: '',
    conference: 'Big 10',
    elo: 5000,
  },
  {
    teamId: 42,
    schoolName: 'University of Oregon',
    city: 'Eugene',
    state: 'Oregon',
    latitude: 44.0448,
    longitude: -123.0726,
    nickname: 'Ducks',
    logo: '',
    conference: 'Big 10',
    elo: 5000,
  },
  {
    teamId: 43,
    schoolName: 'Penn State',
    city: 'University Park',
    state: 'Pennsylvania',
    latitude: 40.7982,
    longitude: -77.859,
    nickname: 'Nittany Lions',
    logo: '',
    conference: 'Big 10',
    elo: 5000,
  },
  {
    teamId: 44,
    schoolName: 'Purdue',
    city: 'West Lafayette',
    state: 'Indiana',
    latitude: 40.4237,
    longitude: -86.9212,
    nickname: 'Boilermakers',
    logo: '',
    conference: 'Big 10',
    elo: 5000,
  },
  {
    teamId: 45,
    schoolName: 'Rutgers',
    city: 'Piscataway',
    state: 'New Jersey',
    latitude: 40.5224,
    longitude: -74.4568,
    nickname: 'Scarlet Knights',
    logo: '',
    conference: 'Big 10',
    elo: 5000,
  },
  {
    teamId: 46,
    schoolName: 'UCLA',
    city: 'Los Angeles',
    state: 'California',
    latitude: 34.0689,
    longitude: -118.4452,
    nickname: 'Bruins',
    logo: '',
    conference: 'Big 10',
    elo: 5000,
  },
  {
    teamId: 47,
    schoolName: 'USC',
    city: 'Los Angeles',
    state: 'California',
    latitude: 34.0226,
    longitude: -118.4957,
    nickname: 'Trojans',
    logo: '',
    conference: 'Big 10',
    elo: 5000,
  },
  {
    teamId: 48,
    schoolName: 'Washington',
    city: 'Seattle',
    state: 'Washington',
    latitude: 47.6537,
    longitude: -122.3078,
    nickname: 'Huskies',
    logo: '',
    conference: 'Big 10',
    elo: 5000,
  },
  {
    teamId: 49,
    schoolName: 'Wisconsin',
    city: 'Madison',
    state: 'Wisconsin',
    latitude: 43.0751,
    longitude: -89.4005,
    nickname: 'Badgers',
    logo: '',
    conference: 'Big 10',
    elo: 5000,
  },
];
