import { Team } from '../../types';

export const big12Teams: Team[] = [
  {
    teamId: 50,
    schoolName: 'Arizona',
    city: 'Tucson',
    state: 'Arizona',
    latitude: 32.2313,
    longitude: -110.9501,
    nickname: 'Wildcats',
    logo: '',
    conference: 'Big 12',
    elo: 5000,
  },
  {
    teamId: 51,
    schoolName: 'Arizona State',
    city: 'Tempe',
    state: 'Arizona',
    latitude: 33.4246,
    longitude: -111.9332,
    nickname: 'Sun Devils',
    logo: '',
    conference: 'Big 12',
    elo: 5000,
  },
  {
    teamId: 52,
    schoolName: 'Baylor',
    city: 'Waco',
    state: 'Texas',
    latitude: 31.5493,
    longitude: -97.1143,
    nickname: 'Bears',
    logo: '',
    conference: 'Big 12',
    elo: 5000,
  },
  {
    teamId: 53,
    schoolName: 'Brigham Young',
    city: 'Provo',
    state: 'Utah',
    latitude: 40.2338,
    longitude: -111.6585,
    nickname: 'Cougars',
    logo: '',
    conference: 'Big 12',
    elo: 5000,
  },
  {
    teamId: 54,
    schoolName: 'Cincinnati',
    city: 'Cincinnati',
    state: 'Ohio',
    latitude: 39.1031,
    longitude: -84.5120,
    nickname: 'Bearcats',
    logo: '',
    conference: 'Big 12',
    elo: 5000,
  },
  {
    teamId: 55,
    schoolName: 'Colorado',
    city: 'Boulder',
    state: 'Colorado',
    latitude: 40.0074,
    longitude: -105.2659,
    nickname: 'Buffaloes',
    logo: '',
    conference: 'Big 12',
    elo: 5000,
  },
  {
    teamId: 56,
    schoolName: 'Houston',
    city: 'Houston',
    state: 'Texas',
    latitude: 29.7604,
    longitude: -95.3698,
    nickname: 'Cougars',
    logo: '',
    conference: 'Big 12',
    elo: 5000,
  },
  {
    teamId: 57,
    schoolName: 'Iowa State',
    city: 'Ames',
    state: 'Iowa',
    latitude: 42.0312,
    longitude: -93.6458,
    nickname: 'Cyclones',
    logo: '',
    conference: 'Big 12',
    elo: 5000,
  },
  {
    teamId: 58,
    schoolName: 'Kansas',
    city: 'Lawrence',
    state: 'Kansas',
    latitude: 38.9784,
    longitude: -95.2658,
    nickname: 'Jayhawks',
    logo: '',
    conference: 'Big 12',
    elo: 5000,
  },
  {
    teamId: 59,
    schoolName: 'Kansas State',
    city: 'Manhattan',
    state: 'Kansas',
    latitude: 39.1869,
    longitude: -96.5717,
    nickname: 'Wildcats',
    logo: '',
    conference: 'Big 12',
    elo: 5000,
  },
  {
    teamId: 60,
    schoolName: 'Oklahoma State',
    city: 'Stillwater',
    state: 'Oklahoma',
    latitude: 36.1131,
    longitude: -97.0589,
    nickname: 'Cowboys',
    logo: '',
    conference: 'Big 12',
    elo: 5000,
  },
  {
    teamId: 61,
    schoolName: 'Texas Christian',
    city: 'Fort Worth',
    state: 'Texas',
    latitude: 32.7084,
    longitude: -97.3575,
    nickname: 'Horned Frogs',
    logo: '',
    conference: 'Big 12',
    elo: 5000,
  },
  {
    teamId: 62,
    schoolName: 'Texas Tech',
    city: 'Lubbock',
    state: 'Texas',
    latitude: 33.5779,
    longitude: -101.8552,
    nickname: 'Red Raiders',
    logo: '',
    conference: 'Big 12',
    elo: 5000,
  },
  {
    teamId: 63,
    schoolName: 'UCF',
    city: 'Orlando',
    state: 'Florida',
    latitude: 28.6024,
    longitude: -81.2001,
    nickname: 'Knights',
    logo: '',
    conference: 'Big 12',
    elo: 5000,
  },
  {
    teamId: 64,
    schoolName: 'Utah',
    city: 'Salt Lake City',
    state: 'Utah',
    latitude: 40.7608,
    longitude: -111.8624,
    nickname: 'Utes',
    logo: '',
    conference: 'Big 12',
    elo: 5000,
  },
  {
    teamId: 65,
    schoolName: 'West Virginia',
    city: 'Morgantown',
    state: 'West Virginia',
    latitude: 39.6295,
    longitude: -79.9559,
    nickname: 'Mountaineers',
    logo: '',
    conference: 'Big 12',
    elo: 5000,
  },
];
