import { Team } from '../../types';

export const cusaTeams: Team[] = [
  {
    teamId: 66,
    schoolName: 'Florida International',
    city: 'Miami',
    state: 'Florida',
    latitude: 25.756,
    longitude: -80.3778,
    nickname: 'Panthers',
    logo: '',
    conference: 'CUSA',
    elo: 5000,
  },
  {
    teamId: 67,
    schoolName: 'Jacksonville State',
    city: 'Jacksonville',
    state: 'Alabama',
    latitude: 33.8248,
    longitude: -85.7625,
    nickname: 'Gamecocks',
    logo: '',
    conference: 'CUSA',
    elo: 5000,
  },
  {
    teamId: 68,
    schoolName: 'Kennesaw State',
    city: 'Kennesaw',
    state: 'Georgia',
    latitude: 34.0294,
    longitude: -84.5833,
    nickname: 'Owls',
    logo: '',
    conference: 'CUSA',
    elo: 5000,
  },
  {
    teamId: 69,
    schoolName: 'Liberty',
    city: 'Lynchburg',
    state: 'Virginia',
    latitude: 37.3513,
    longitude: -79.1805,
    nickname: 'Flames',
    logo: '',
    conference: 'CUSA',
    elo: 5000,
  },
  {
    teamId: 70,
    schoolName: 'Middle Tennessee State',
    city: 'Murfreesboro',
    state: 'Tennessee',
    latitude: 35.8497,
    longitude: -86.3926,
    nickname: 'Blue Raiders',
    logo: '',
    conference: 'CUSA',
    elo: 5000,
  },
  {
    teamId: 71,
    schoolName: 'New Mexico State',
    city: 'Las Cruces',
    state: 'New Mexico',
    latitude: 32.2818,
    longitude: -106.749,
    nickname: 'Aggies',
    logo: '',
    conference: 'CUSA',
    elo: 5000,
  },
  {
    teamId: 72,
    schoolName: 'Sam Houston State',
    city: 'Huntsville',
    state: 'Texas',
    latitude: 30.7107,
    longitude: -95.5495,
    nickname: 'Bearkats',
    logo: '',
    conference: 'CUSA',
    elo: 5000,
  },
  {
    teamId: 73,
    schoolName: 'Louisiana Tech',
    city: 'Ruston',
    state: 'Louisiana',
    latitude: 32.5293,
    longitude: -92.6353,
    nickname: 'Bulldogs',
    logo: '',
    conference: 'CUSA',
    elo: 5000,
  },
  {
    teamId: 74,
    schoolName: 'UTEP',
    city: 'El Paso',
    state: 'Texas',
    latitude: 31.7776,
    longitude: -106.5043,
    nickname: 'Miners',
    logo: '',
    conference: 'CUSA',
    elo: 5000,
  },
  {
    teamId: 75,
    schoolName: 'Western Kentucky',
    city: 'Bowling Green',
    state: 'Kentucky',
    latitude: 36.9902,
    longitude: -86.4436,
    nickname: 'Hilltoppers',
    logo: '',
    conference: 'CUSA',
    elo: 5000,
  },
];
