import { Team } from '../../types';

export const indTeams: Team[] = [
{
    teamId: 77,
    schoolName: 'Notre Dame',
    city: 'Notre Dame',
    state: 'Indiana',
    latitude: 41.7034,
    longitude: -86.2254,
    nickname: 'Fighting Irish',
    logo: '',
    conference: 'Independent',
    elo: 5000,
    },
  {
    teamId: 76,
    schoolName: 'UConn',
    city: 'Storrs',
    state: 'Connecticut',
    latitude: 41.8084,
    longitude: -72.2538,
    nickname: 'Huskies',
    logo: '',
    conference: 'Independent',
    elo: 5000,
  },
  {
    teamId: 78,
    schoolName: 'UMass',
    city: 'Amherst',
    state: 'Massachusetts',
    latitude: 42.3905,
    longitude: -72.5292,
    nickname: 'Minutemen',
    logo: '',
    conference: 'Independent',
    elo: 5000,
  },
];
