import { Team } from '../../types';

export const macTeams: Team[] = [
  {
    teamId: 79,
    schoolName: 'Akron',
    city: 'Akron',
    state: 'Ohio',
    latitude: 41.0814,
    longitude: -81.5190,
    nickname: 'Zips',
    logo: '',
    conference: 'MAC',
    elo: 5000,
  },
  {
    teamId: 80,
    schoolName: 'Ball State',
    city: 'Muncie',
    state: 'Indiana',
    latitude: 40.1934,
    longitude: -85.4148,
    nickname: 'Cardinals',
    logo: '',
    conference: 'MAC',
    elo: 5000,
  },
  {
    teamId: 81,
    schoolName: 'Buffalo',
    city: 'Buffalo',
    state: 'New York',
    latitude: 42.8864,
    longitude: -78.8784,
    nickname: 'Bulls',
    logo: '',
    conference: 'MAC',
    elo: 5000,
  },
  {
    teamId: 82,
    schoolName: 'Bowling Green',
    city: 'Bowling Green',
    state: 'Ohio',
    latitude: 41.3760,
    longitude: -83.6301,
    nickname: 'Falcons',
    logo: '',
    conference: 'MAC',
    elo: 5000,
  },
  {
    teamId: 83,
    schoolName: 'Central Michigan',
    city: 'Mount Pleasant',
    state: 'Michigan',
    latitude: 43.5893,
    longitude: -84.7666,
    nickname: 'Chippewas',
    logo: '',
    conference: 'MAC',
    elo: 5000,
  },
  {
    teamId: 84,
    schoolName: 'Eastern Michigan',
    city: 'Ypsilanti',
    state: 'Michigan',
    latitude: 42.2587,
    longitude: -81.0540,
    nickname: 'Eagles',
    logo: '',
    conference: 'MAC',
    elo: 5000,
  },
  {
    teamId: 85,
    schoolName: 'Kent State',
    city: 'Kent',
    state: 'Ohio',
    latitude: 41.1481,
    longitude: -81.3431,
    nickname: 'Golden Flashes',
    logo: '',
    conference: 'MAC',
    elo: 5000,
  },
  {
    teamId: 86,
    schoolName: 'Miami OH',
    city: 'Oxford',
    state: 'Ohio',
    latitude: 39.5075,
    longitude: -84.7446,
    nickname: 'RedHawks',
    logo: '',
    conference: 'MAC',
    elo: 5000,
  },
  {
    teamId: 87,
    schoolName: 'Northern Illinois',
    city: 'DeKalb',
    state: 'Illinois',
    latitude: 41.9332,
    longitude: -88.7685,
    nickname: 'Huskies',
    logo: '',
    conference: 'MAC',
    elo: 5000,
  },
  {
    teamId: 88,
    schoolName: 'Ohio',
    city: 'Athens',
    state: 'Ohio',
    latitude: 39.3240,
    longitude: -82.1012,
    nickname: 'Bobcats',
    logo: '',
    conference: 'MAC',
    elo: 5000,
  },
  {
    teamId: 89,
    schoolName: 'Toledo',
    city: 'Toledo',
    state: 'Ohio',
    latitude: 41.6603,
    longitude: -83.5379,
    nickname: 'Rockets',
    logo: '',
    conference: 'MAC',
    elo: 5000,
  },
  {
    teamId: 90,
    schoolName: 'Western Michigan',
    city: 'Kalamazoo',
    state: 'Michigan',
    latitude: 42.2917,
    longitude: -85.5872,
    nickname: 'Broncos',
    logo: '',
    conference: 'MAC',
    elo: 5000,
  },
];
