import { Team } from '../../types';

export const mwTeams: Team[] = [
  {
    teamId: 91,
    schoolName: 'Air Force',
    city: 'Colorado Springs',
    state: 'Colorado',
    latitude: 38.9977,
    longitude: -104.8521,
    nickname: 'Falcons',
    logo: '',
    conference: 'MW',
    elo: 5000,
  },
  {
    teamId: 92,
    schoolName: 'Boise State',
    city: 'Boise',
    state: 'Idaho',
    latitude: 43.6187,
    longitude: -116.2146,
    nickname: 'Broncos',
    logo: '',
    conference: 'MW',
    elo: 5000,
  },
  {
    teamId: 93,
    schoolName: 'Colorado State',
    city: 'Fort Collins',
    state: 'Colorado',
    latitude: 40.5734,
    longitude: -105.0844,
    nickname: 'Rams',
    logo: '',
    conference: 'MW',
    elo: 5000,
  },
  {
    teamId: 94,
    schoolName: 'Fresno State',
    city: 'Fresno',
    state: 'California',
    latitude: 36.7468,
    longitude: -119.7726,
    nickname: 'Bulldogs',
    logo: '',
    conference: 'MW',
    elo: 5000,
  },
  {
    teamId: 95,
    schoolName: 'Hawaii',
    city: 'Honolulu',
    state: 'Hawaii',
    latitude: 21.3069,
    longitude: -157.8583,
    nickname: 'Rainbow Warriors',
    logo: '',
    conference: 'MW',
    elo: 5000,
  },
  {
    teamId: 96,
    schoolName: 'Nevada',
    city: 'Reno',
    state: 'Nevada',
    latitude: 39.5296,
    longitude: -119.8138,
    nickname: 'Wolf Pack',
    logo: '',
    conference: 'MW',
    elo: 5000,
  },
  {
    teamId: 97,
    schoolName: 'New Mexico',
    city: 'Albuquerque',
    state: 'New Mexico',
    latitude: 35.0844,
    longitude: -106.6504,
    nickname: 'Lobos',
    logo: '',
    conference: 'MW',
    elo: 5000,
  },
  {
    teamId: 98,
    schoolName: 'San Diego State',
    city: 'San Diego',
    state: 'California',
    latitude: 32.7157,
    longitude: -117.1611,
    nickname: 'Aztecs',
    logo: '',
    conference: 'MW',
    elo: 5000,
  },
  {
    teamId: 99,
    schoolName: 'San Jose State',
    city: 'San Jose',
    state: 'California',
    latitude: 37.3382,
    longitude: -121.8863,
    nickname: 'Spartans',
    logo: '',
    conference: 'MW',
    elo: 5000,
  },
  {
    teamId: 100,
    schoolName: 'UNLV',
    city: 'Las Vegas',
    state: 'Nevada',
    latitude: 36.1699,
    longitude: -115.1398,
    nickname: 'Rebels',
    logo: '',
    conference: 'MW',
    elo: 5000,
  },
  {
    teamId: 101,
    schoolName: 'Utah State',
    city: 'Logan',
    state: 'Utah',
    latitude: 41.7359,
    longitude: -111.8340,
    nickname: 'Aggies',
    logo: '',
    conference: 'MW',
    elo: 5000,
  },
  {
    teamId: 102,
    schoolName: 'Wyoming',
    city: 'Laramie',
    state: 'Wyoming',
    latitude: 41.3111,
    longitude: -105.5911,
    nickname: 'Cowboys',
    logo: '',
    conference: 'MW',
    elo: 5000,
  },
];
