import { Team } from '../../types';

export const secTeams: Team[] = [
  {
    teamId: 105,
    schoolName: 'Alabama',
    city: 'Tuscaloosa',
    state: 'Alabama',
    latitude: 33.2148,
    longitude: -87.5469,
    nickname: 'Crimson Tide',
    logo: '',
    conference: 'SEC',
    elo: 5000,
  },
  {
    teamId: 106,
    schoolName: 'Arkansas',
    city: 'Fayetteville',
    state: 'Arkansas',
    latitude: 36.0520,
    longitude: -94.1719,
    nickname: 'Razorbacks',
    logo: '',
    conference: 'SEC',
    elo: 5000,
  },
  {
    teamId: 107,
    schoolName: 'Auburn',
    city: 'Auburn',
    state: 'Alabama',
    latitude: 32.6099,
    longitude: -85.4808,
    nickname: 'Tigers',
    logo: '',
    conference: 'SEC',
    elo: 5000,
  },
  {
    teamId: 108,
    schoolName: 'Florida',
    city: 'Gainesville',
    state: 'Florida',
    latitude: 29.6516,
    longitude: -82.3248,
    nickname: 'Gators',
    logo: '',
    conference: 'SEC',
    elo: 5000,
  },
  {
    teamId: 109,
    schoolName: 'Georgia',
    city: 'Athens',
    state: 'Georgia',
    latitude: 33.9510,
    longitude: -83.3730,
    nickname: 'Bulldogs',
    logo: '',
    conference: 'SEC',
    elo: 5000,
  },
  {
    teamId: 110,
    schoolName: 'Kentucky',
    city: 'Lexington',
    state: 'Kentucky',
    latitude: 38.0368,
    longitude: -84.5051,
    nickname: 'Wildcats',
    logo: '',
    conference: 'SEC',
    elo: 5000,
  },
  {
    teamId: 111,
    schoolName: 'LSU',
    city: 'Baton Rouge',
    state: 'Louisiana',
    latitude: 30.3960,
    longitude: -91.1790,
    nickname: 'Tigers',
    logo: '',
    conference: 'SEC',
    elo: 5000,
  },
  {
    teamId: 112,
    schoolName: 'Mississippi State',
    city: 'Starkville',
    state: 'Mississippi',
    latitude: 33.4553,
    longitude: -88.7894,
    nickname: 'Bulldogs',
    logo: '',
    conference: 'SEC',
    elo: 5000,
  },
  {
    teamId: 113,
    schoolName: 'Missouri',
    city: 'Columbia',
    state: 'Missouri',
    latitude: 38.9521,
    longitude: -92.3341,
    nickname: 'Tigers',
    logo: '',
    conference: 'SEC',
    elo: 5000,
  },
  {
    teamId: 114,
    schoolName: 'Ole Miss',
    city: 'Oxford',
    state: 'Mississippi',
    latitude: 34.3664,
    longitude: -89.5192,
    nickname: 'Rebels',
    logo: '',
    conference: 'SEC',
    elo: 5000,
  },
  {
    teamId: 115,
    schoolName: 'Oklahoma',
    city: 'Norman',
    state: 'Oklahoma',
    latitude: 35.2226,
    longitude: -97.4395,
    nickname: 'Sooners',
    logo: '',
    conference: 'SEC',
    elo: 5000,
  },
  {
    teamId: 116,
    schoolName: 'South Carolina',
    city: 'Columbia',
    state: 'South Carolina',
    latitude: 33.9908,
    longitude: -81.0255,
    nickname: 'Gamecocks',
    logo: '',
    conference: 'SEC',
    elo: 5000,
  },
  {
    teamId: 117,
    schoolName: 'Tennessee',
    city: 'Knoxville',
    state: 'Tennessee',
    latitude: 35.9606,
    longitude: -83.9207,
    nickname: 'Volunteers',
    logo: '',
    conference: 'SEC',
    elo: 5000,
  },
  {
    teamId: 118,
    schoolName: 'Texas A&M',
    city: 'College Station',
    state: 'Texas',
    latitude: 30.6120,
    longitude: -96.3418,
    nickname: 'Aggies',
    logo: '',
    conference: 'SEC',
    elo: 5000,
  },
  {
    teamId: 119,
    schoolName: 'Texas',
    city: 'Austin',
    state: 'Texas',
    latitude: 30.2672,
    longitude: -97.7431,
    nickname: 'Longhorns',
    logo: '',
    conference: 'SEC',
    elo: 5000,
  },
  {
    teamId: 120,
    schoolName: 'Vanderbilt',
    city: 'Nashville',
    state: 'Tennessee',
    latitude: 36.1447,
    longitude: -86.8085,
    nickname: 'Commodores',
    logo: '',
    conference: 'SEC',
    elo: 5000,
  },
];
