import { Team } from '../../types';

export const sunbeltTeams: Team[] = [
  {
    teamId: 121,
    schoolName: 'Appalachian State',
    city: 'Boone',
    state: 'North Carolina',
    latitude: 36.2131,
    longitude: -81.6746,
    nickname: 'Mountaineers',
    logo: '',
    conference: 'Sun Belt',
    elo: 5000,
  },
  {
    teamId: 122,
    schoolName: 'Arkansas State',
    city: 'Jonesboro',
    state: 'Arkansas',
    latitude: 35.8423,
    longitude: -90.7043,
    nickname: 'Red Wolves',
    logo: '',
    conference: 'Sun Belt',
    elo: 5000,
  },
  {
    teamId: 123,
    schoolName: 'Coastal Carolina',
    city: 'Conway',
    state: 'South Carolina',
    latitude: 33.8431,
    longitude: -79.0518,
    nickname: 'Chanticleers',
    logo: '',
    conference: 'Sun Belt',
    elo: 5000,
  },
  {
    teamId: 124,
    schoolName: 'Georgia Southern',
    city: 'Statesboro',
    state: 'Georgia',
    latitude: 32.4406,
    longitude: -81.7835,
    nickname: 'Eagles',
    logo: '',
    conference: 'Sun Belt',
    elo: 5000,
  },
  {
    teamId: 125,
    schoolName: 'Georgia State',
    city: 'Atlanta',
    state: 'Georgia',
    latitude: 33.7490,
    longitude: -84.3880,
    nickname: 'Panthers',
    logo: '',
    conference: 'Sun Belt',
    elo: 5000,
  },
  {
    teamId: 126,
    schoolName: 'James Madison',
    city: 'Harrisonburg',
    state: 'Virginia',
    latitude: 38.4342,
    longitude: -78.8689,
    nickname: 'Dukes',
    logo: '',
    conference: 'Sun Belt',
    elo: 5000,
  },
  {
    teamId: 127,
    schoolName: 'Louisiana-Lafayette',
    city: 'Lafayette',
    state: 'Louisiana',
    latitude: 30.2241,
    longitude: -92.0198,
    nickname: 'Ragin\' Cajuns',
    logo: '',
    conference: 'Sun Belt',
    elo: 5000,
  },
  {
    teamId: 128,
    schoolName: 'Louisiana-Monroe',
    city: 'Monroe',
    state: 'Louisiana',
    latitude: 32.5093,
    longitude: -92.1193,
    nickname: 'Warhawks',
    logo: '',
    conference: 'Sun Belt',
    elo: 5000,
  },
  {
    teamId: 129,
    schoolName: 'Marshall',
    city: 'Huntington',
    state: 'West Virginia',
    latitude: 38.4193,
    longitude: -82.4452,
    nickname: 'Thundering Herd',
    logo: '',
    conference: 'Sun Belt',
    elo: 5000,
  },
  {
    teamId: 130,
    schoolName: 'Old Dominion',
    city: 'Norfolk',
    state: 'Virginia',
    latitude: 36.8573,
    longitude: -76.2852,
    nickname: 'Monarchs',
    logo: '',
    conference: 'Sun Belt',
    elo: 5000,
  },
  {
    teamId: 131,
    schoolName: 'South Alabama',
    city: 'Mobile',
    state: 'Alabama',
    latitude: 30.6954,
    longitude: -88.0399,
    nickname: 'Jaguars',
    logo: '',
    conference: 'Sun Belt',
    elo: 5000,
  },
  {
    teamId: 134,
    schoolName: 'Southern Miss',
    city: 'Hattiesburg',
    state: 'Mississippi',
    latitude: 31.3221,
    longitude: -89.3085,
    nickname: 'Golden Eagles',
    logo: '',
    conference: 'Sun Belt',
    elo: 5000,
  },
  {
    teamId: 132,
    schoolName: 'Troy',
    city: 'Troy',
    state: 'Alabama',
    latitude: 31.8111,
    longitude: -85.9514,
    nickname: 'Trojans',
    logo: '',
    conference: 'Sun Belt',
    elo: 5000,
  },
  {
    teamId: 133,
    schoolName: 'Texas State',
    city: 'San Marcos',
    state: 'Texas',
    latitude: 29.8882,
    longitude: -97.9414,
    nickname: 'Bobcats',
    logo: '',
    conference: 'Sun Belt',
    elo: 5000,
  }
];
